# Generated by Django 5.2.10 on 2026-01-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='groupe_responsable',
        ),
    ]
